/**
 * Rasterise the brand.
 *
 *   node tools/render_brand.mjs
 *
 * The insignia is authored once, as SVG, in lib/insignia.ts. This imports that
 * same module — Node strips the types — and renders it through headless Chrome
 * at every size the metadata needs, so the favicon, the app icons and the
 * social card are all the same drawing. Nothing here is generated at build
 * time; the outputs are committed, because a clone should not need a browser.
 *
 * Re-run it after touching lib/insignia.ts or lib/brand.ts.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import puppeteer from "puppeteer-core";

import { BRAND, SITE } from "../lib/brand.ts";
import { INSIGNIA_SVG } from "../lib/insignia.ts";

const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (...p) => join(ROOT, ...p);

const dataUri = (rel) =>
  `data:image/jpeg;base64,${readFileSync(at(rel)).toString("base64")}`;

/** The SVG file itself is an output too: Next serves it as the favicon. */
writeFileSync(
  at("app/icon.svg"),
  `<!-- Generated by tools/render_brand.mjs from lib/insignia.ts. Do not edit. -->\n${INSIGNIA_SVG}\n`
);

const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: true,
  args: ["--hide-scrollbars", "--force-device-scale-factor=1"],
});

async function shoot(html, { width, height, out, transparent = false, quality }) {
  const page = await browser.newPage();
  await page.setViewport({ width, height, deviceScaleFactor: 1 });
  await page.setContent(
    `<!doctype html><meta charset="utf-8"><style>
       *{margin:0;padding:0;box-sizing:border-box}
       html,body{width:${width}px;height:${height}px;overflow:hidden;
         background:${transparent ? "transparent" : SITE.themeColor}}
       svg{display:block}
     </style>${html}`,
    { waitUntil: "load" }
  );
  // Fonts and the radial gradient want one frame to settle.
  await new Promise((r) => setTimeout(r, 260));
  mkdirSync(dirname(at(out)), { recursive: true });
  await page.screenshot(
    quality
      ? { path: at(out), type: "jpeg", quality }
      : { path: at(out), omitBackground: transparent }
  );
  await page.close();
  console.log(`  ${out}  ${width}×${height}`);
}

/** The badge alone, filling the frame. */
const badge = (px) =>
  `<div style="width:${px}px;height:${px}px">${INSIGNIA_SVG.replace(
    "<svg ",
    `<svg width="${px}" height="${px}" `
  )}</div>`;

/** The badge inset on a solid square, for platforms that crop or letterbox. */
const badgeOn = (px, inset) => `
  <div style="width:${px}px;height:${px}px;background:${SITE.themeColor};
              display:flex;align-items:center;justify-content:center">
    ${badge(Math.round(px * inset))}
  </div>`;

console.log("icons");
await shoot(badge(512), { width: 512, height: 512, out: "public/brand/icon-512.png", transparent: true });
await shoot(badge(192), { width: 192, height: 192, out: "public/brand/icon-192.png", transparent: true });
await shoot(badge(256), { width: 256, height: 256, out: "docs/images/insignia.png", transparent: true });
// A raster fallback beside app/icon.svg, for browsers too old to take an SVG.
await shoot(badge(48), { width: 48, height: 48, out: "app/icon1.png", transparent: true });
// Safari fills a transparent Apple touch icon with black; give it its own ground.
await shoot(badgeOn(180, 0.86), { width: 180, height: 180, out: "app/apple-icon.png" });
// Android maskable icons are cropped to an unknown shape; keep clear of the edge.
await shoot(badgeOn(512, 0.6), { width: 512, height: 512, out: "public/brand/maskable-512.png" });

console.log("social card");
const card = `
  <div style="position:relative;width:1200px;height:630px;overflow:hidden;
              background:${SITE.themeColor};font-family:'Helvetica Neue',Arial,sans-serif">
    <img src="${dataUri("docs/images/sunset.jpg")}"
         style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;
                filter:saturate(1.1) contrast(1.03) brightness(1.18)">
    <div style="position:absolute;inset:0;background:
         linear-gradient(100deg, rgba(8,5,4,0.93) 0%, rgba(8,5,4,0.7) 44%, rgba(8,5,4,0.06) 100%)"></div>
    <div style="position:absolute;inset:0;background:
         linear-gradient(0deg, rgba(8,5,4,0.86) 0%, rgba(8,5,4,0) 42%)"></div>

    <div style="position:absolute;left:76px;top:64px;display:flex;align-items:center;gap:20px">
      ${badge(84)}
      <div style="line-height:1.5">
        <div style="font-size:19px;letter-spacing:0.2em;color:#f0d4b4;text-transform:uppercase">
          ${BRAND.agency}</div>
        <div style="font-size:14px;letter-spacing:0.26em;color:#a87d5e;text-transform:uppercase">
          ${BRAND.division} &middot; ${BRAND.mission}</div>
      </div>
    </div>

    <div style="position:absolute;left:76px;top:236px;right:76px">
      <div style="font-size:104px;font-weight:700;letter-spacing:-0.02em;color:#fff;line-height:1">
        Gale Crater</div>
      <div style="margin-top:22px;font-size:31px;color:#f0d4b4;letter-spacing:0.005em">
        Drive a Mars rover in your browser.</div>
      <div style="margin-top:16px;font-size:19px;letter-spacing:0.13em;color:#ff9d4d;text-transform:uppercase">
        Real MOLA elevation &nbsp;·&nbsp; rocker-bogie suspension &nbsp;·&nbsp; 4.2 cm&#8202;/&#8202;s
      </div>
    </div>

    <div style="position:absolute;left:76px;right:76px;bottom:52px;display:flex;
                align-items:flex-end;justify-content:space-between">
      <div style="font-family:ui-monospace,'SF Mono',Menlo,monospace;font-size:17px;
                  letter-spacing:0.1em;color:#f0d4b4">oddurs.github.io/rover</div>
      <div style="font-family:ui-monospace,'SF Mono',Menlo,monospace;font-size:12px;
                  letter-spacing:0.09em;color:#6d5241;text-align:right;max-width:430px;line-height:1.6">
        ${BRAND.disclaimerShort.toUpperCase()}</div>
    </div>

    <div style="position:absolute;left:0;right:0;bottom:0;height:4px;
                background:linear-gradient(90deg,#ff9d4d 0%,#e8552f 52%,rgba(232,85,47,0) 100%)"></div>
  </div>`;

// JPEG, not PNG: the card is mostly a photograph, and the same frame costs a
// fifth as much. Both are committed, so the saving is in everyone's clone.
await shoot(card, { width: 1200, height: 630, out: "app/opengraph-image.jpg", quality: 90 });
copyFileSync(at("app/opengraph-image.jpg"), at("app/twitter-image.jpg"));
console.log("  app/twitter-image.jpg  (copy)");

await browser.close();
